// Generated by gencpp from file learn_commucation/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARN_COMMUCATION_MESSAGE_ADDTWOINTS_H
#define LEARN_COMMUCATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learn_commucation/AddTwoIntsRequest.h>
#include <learn_commucation/AddTwoIntsResponse.h>


namespace learn_commucation
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learn_commucation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learn_commucation::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learn_commucation::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learn_commucation::AddTwoInts > {
  static const char* value()
  {
    return "learn_commucation/AddTwoInts";
  }

  static const char* value(const ::learn_commucation::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learn_commucation::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learn_commucation::AddTwoInts > 
template<>
struct MD5Sum< ::learn_commucation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learn_commucation::AddTwoInts >::value();
  }
  static const char* value(const ::learn_commucation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_commucation::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learn_commucation::AddTwoInts > 
template<>
struct DataType< ::learn_commucation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learn_commucation::AddTwoInts >::value();
  }
  static const char* value(const ::learn_commucation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learn_commucation::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learn_commucation::AddTwoInts > 
template<>
struct MD5Sum< ::learn_commucation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learn_commucation::AddTwoInts >::value();
  }
  static const char* value(const ::learn_commucation::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_commucation::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learn_commucation::AddTwoInts > 
template<>
struct DataType< ::learn_commucation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learn_commucation::AddTwoInts >::value();
  }
  static const char* value(const ::learn_commucation::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARN_COMMUCATION_MESSAGE_ADDTWOINTS_H
